import { useEffect, useMemo, useState } from 'react';
import { Activity, Boxes, Cable, Gauge, LayoutDashboard, LogOut, Network, RefreshCw, Settings, Shield, Users, Zap } from 'lucide-react';
import { api, unwrapList } from './api';
import { bytes, dateTime, isAdmin, percent } from './format';
import type { DashboardData, ForwardInfo, NodeInfo, SpeedLimitInfo, TunnelInfo, UserInfo } from './types';
type Page='dashboard'|'nodes'|'tunnels'|'forwards'|'users'|'limits'|'config';
const empty:DashboardData={nodes:[],tunnels:[],forwards:[],users:[],limits:[]};
const nav=[['dashboard','总览',LayoutDashboard],['forwards','转发',Cable],['tunnels','隧道',Network],['nodes','节点',Boxes],['users','用户',Users],['limits','限速',Gauge],['config','配置',Settings]] as const;
const good=(status?:number)=>status===1?'ok':status===0?'off':'warn';
export default function App(){
 const[token,setToken]=useState(localStorage.getItem('token')); const[page,setPage]=useState<Page>('dashboard'); const[data,setData]=useState(empty); const[loading,setLoading]=useState(false); const[msg,setMsg]=useState(''); const[user,setUser]=useState(''); const[pwd,setPwd]=useState(''); const admin=isAdmin();
 const load=async()=>{setLoading(true); const[n,t,f,u,l]=await Promise.all([api.nodes(),api.tunnels(),api.forwards(),admin?api.users():Promise.resolve({code:0,msg:'',data:[] as UserInfo[]}),admin?api.limits():Promise.resolve({code:0,msg:'',data:[] as SpeedLimitInfo[]})]); setData({nodes:unwrapList(n),tunnels:unwrapList(t),forwards:unwrapList(f),users:unwrapList(u),limits:unwrapList(l)}); const bad=[n,t,f,u,l].find(x=>x.code!==0&&x.code!==200); setMsg(bad?.msg||''); setLoading(false)};
 useEffect(()=>{if(token)load()},[token]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);const r=await api.login({username:user,password:pwd,captchaId:''});setLoading(false);if(r.code===0||r.code===200){localStorage.setItem('token',r.data.token);localStorage.setItem('role_id',String(r.data.role_id));localStorage.setItem('name',r.data.name||user);setToken(r.data.token)}else setMsg(r.msg)};
 const action=async(label:string,fn:()=>Promise<{code:number;msg:string}>)=>{if(!confirm(`确定${label}？`))return;const r=await fn();setMsg(r.msg||`${label}完成`);load()};
 const stats=useMemo(()=>({online:data.nodes.filter(n=>n.online??n.status===1).length,active:data.forwards.filter(f=>f.status===1).length,traffic:data.forwards.reduce((s,f)=>s+Number(f.inFlow||0)+Number(f.outFlow||0),0)}),[data]);
 if(!token)return <main className="login"><section className="login-art"><div className="brand-orb"><Zap/></div><p className="eyebrow">FLUX PANEL ENHANCED</p><h1>连接每一条<br/>重要的链路</h1><p>节点、隧道与转发的统一控制平面</p><div className="signal"><i/><i/><i/><i/></div></section><form className="login-card" onSubmit={login}><Shield size={34}/><h2>欢迎回来</h2><p>登录到你的网络控制台</p><label>用户名<input value={user} onChange={e=>setUser(e.target.value)} required autoFocus/></label><label>密码<input type="password" value={pwd} onChange={e=>setPwd(e.target.value)} required/></label>{msg&&<div className="notice">{msg}</div>}<button disabled={loading}>{loading?'连接中…':'进入面板'}</button></form></main>;
 return <div className="shell"><aside><div className="logo"><div><Zap/></div><span>Flux<small>Panel</small></span></div><nav>{nav.filter(([k])=>admin||!['nodes','tunnels','users','limits','config'].includes(k)).map(([k,label,Icon])=><button className={page===k?'active':''} onClick={()=>setPage(k as Page)} key={k}><Icon/>{label}</button>)}</nav><div className="account"><span className="avatar">{(localStorage.getItem('name')||'U')[0]}</span><div><b>{localStorage.getItem('name')||'用户'}</b><small>{admin?'管理员':'普通用户'}</small></div><button onClick={()=>{localStorage.clear();setToken(null)}}><LogOut/></button></div></aside><main className="content"><header><div><p className="eyebrow">NETWORK CONTROL CENTER</p><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div><button className="refresh" onClick={load}><RefreshCw className={loading?'spin':''}/>刷新数据</button></header>{msg&&<div className="notice">{msg}</div>}{page==='dashboard'&&<><section className="hero"><div><span className="live"><i/> SYSTEM OPERATIONAL</span><h2>网络运行平稳</h2><p>{stats.online} 个节点在线，{stats.active} 条转发正在工作</p></div><Activity/></section><section className="stats"><Stat label="在线节点" value={`${stats.online}/${data.nodes.length}`} icon={<Boxes/>}/><Stat label="活动转发" value={String(stats.active)} icon={<Cable/>}/><Stat label="隧道总数" value={String(data.tunnels.length)} icon={<Network/>}/><Stat label="累计流量" value={bytes(stats.traffic)} icon={<Gauge/>}/></section><section className="grid"><Panel title="节点健康"><NodeRows rows={data.nodes.slice(0,6)}/></Panel><Panel title="最近转发"><ForwardRows rows={data.forwards.slice(0,6)} action={action}/></Panel></section></>}{page==='nodes'&&<Panel title="节点列表" wide><NodeRows rows={data.nodes}/></Panel>}{page==='tunnels'&&<Panel title="隧道列表" wide><TunnelRows rows={data.tunnels} action={action}/></Panel>}{page==='forwards'&&<Panel title="转发列表" wide><ForwardRows rows={data.forwards} action={action}/></Panel>}{page==='users'&&<Panel title="用户列表" wide><UserRows rows={data.users}/></Panel>}{page==='limits'&&<Panel title="限速规则" wide><LimitRows rows={data.limits}/></Panel>}{page==='config'&&<ConfigPanel/>}</main></div>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <article className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></article>}
function Panel({title,children,wide}:{title:string;children:React.ReactNode;wide?:boolean}){return <section className={`panel ${wide?'wide':''}`}><div className="panel-head"><h3>{title}</h3><span>实时数据</span></div>{children}</section>}
function NodeRows({rows}:{rows:NodeInfo[]}){return <div className="rows">{rows.map(n=><div className="row" key={n.id}><span className={`dot ${good(n.online?1:n.status)}`}/><div className="grow"><b>{n.name}</b><small>{n.serverIp||n.ip||'未设置地址'} · v{n.version||'—'}</small></div><Meter value={n.cpuUsage} label="CPU"/><Meter value={n.memoryUsage} label="内存"/><span className="meta">{n.cpuCores||'—'} 核<br/>{bytes(n.memoryTotal)}</span></div>)}{!rows.length&&<Empty/>}</div>}
function TunnelRows({rows,action}:{rows:TunnelInfo[];action:any}){return <div className="table"><div className="tr th"><span>名称</span><span>协议</span><span>入口</span><span>出口</span><span>倍率</span><span>操作</span></div>{rows.map(t=><div className="tr" key={t.id}><span><b>{t.name}</b></span><span><em>{t.protocol||'TCP/UDP'}</em></span><span>{t.entryNodeIds?.length||1} 个入口</span><span>{t.outIp||`节点 #${t.outNodeId||'—'}`}</span><span>{t.trafficRatio||1}×</span><span><button className="mini" onClick={()=>action('诊断隧道',()=>api.diagnoseTunnel(t.id))}>诊断</button></span></div>)}{!rows.length&&<Empty/>}</div>}
function ForwardRows({rows,action}:{rows:ForwardInfo[];action:any}){return <div className="rows">{rows.map(f=><div className="row" key={f.id}><span className={`dot ${good(f.status)}`}/><div className="grow"><b>{f.name}</b><small>{f.inIp||'入口'}:{f.inPort||'—'} → {f.remoteAddr||'—'}</small></div><span className="meta">{f.tunnelName||`隧道 #${f.tunnelId||'—'}`}<br/>{bytes(Number(f.inFlow||0)+Number(f.outFlow||0))}</span><button className="mini" onClick={()=>action(f.status===1?'暂停转发':'恢复转发',()=>f.status===1?api.pauseForward(f.id):api.resumeForward(f.id))}>{f.status===1?'暂停':'恢复'}</button></div>)}{!rows.length&&<Empty/>}</div>}
function UserRows({rows}:{rows:UserInfo[]}){return <div className="table"><div className="tr th"><span>用户</span><span>状态</span><span>转发配额</span><span>流量</span><span>到期时间</span><span>角色</span></div>{rows.map(u=><div className="tr" key={u.id}><span><b>{u.user}</b></span><span><em className={good(u.status)}>{u.status===1?'启用':'停用'}</em></span><span>{u.num??'—'}</span><span>{bytes(Number(u.inFlow||0)+Number(u.outFlow||0))} / {u.flow??'∞'} GB</span><span>{dateTime(u.expTime)}</span><span>{u.roleId===0?'管理员':'用户'}</span></div>)}{!rows.length&&<Empty/>}</div>}
function LimitRows({rows}:{rows:SpeedLimitInfo[]}){return <div className="table"><div className="tr th"><span>规则</span><span>速率</span><span>隧道</span><span>状态</span><span></span><span></span></div>{rows.map(l=><div className="tr" key={l.id}><span><b>{l.name}</b></span><span>{l.speed} Mbps</span><span>{l.tunnelName||`#${l.tunnelId||'全部'}`}</span><span><em className={good(l.status)}>{l.status===0?'停用':'启用'}</em></span><span></span><span></span></div>)}{!rows.length&&<Empty/>}</div>}
function ConfigPanel(){const[name,setName]=useState('app_name');const[value,setValue]=useState('');const[msg,setMsg]=useState('');useEffect(()=>{api.config(name).then(r=>setValue(typeof r.data==='string'?r.data:''))},[]);return <Panel title="网站配置" wide><form className="config-form" onSubmit={async e=>{e.preventDefault();const r=await api.updateConfig(name,value);setMsg(r.msg||'已保存')}}><label>配置项<input value={name} onChange={e=>setName(e.target.value)}/></label><label>配置值<input value={value} onChange={e=>setValue(e.target.value)}/></label><button>保存配置</button>{msg&&<span>{msg}</span>}</form></Panel>}
function Meter({value,label}:{value?:number;label:string}){return <span className="meter"><small>{label} {percent(value)}</small><i><b style={{width:percent(value)}}/></i></span>}
function Empty(){return <div className="empty">暂无数据</div>}
